-- Insert multiple users in a single statement
INSERT INTO users (id, name, img, username, email, password, role, enabled, created_at, updated_at, created_by,
                   updated_by)
VALUES (gen_random_uuid(),
        'superadmin',
        'haha.jpg',
        'admin',
        'admin@example.com',
        '$2a$10$SLFWIgDoFq49uquyFJDoReLBUcVmElHLISAfXp/TgY3EwN07VCRsC',
        'ADMIN',
        true,
        now(),
        now(),
        'system',
        'system'),
       (gen_random_uuid(),
        'Bac si Minh',
        'haha.jpg',
        'doctor',
        'doctor@example.com',
        '$2a$10$SLFWIgDoFq49uquyFJDoReLBUcVmElHLISAfXp/TgY3EwN07VCRsC',
        'DOCTOR',
        true,
        now(),
        now(),
        'system',
        'system'),
       (gen_random_uuid(),
        'Nhan vien Minh',
        'haha.jpg',
        'cashier',
        'cashier@example.com',
        '$2a$10$SLFWIgDoFq49uquyFJDoReLBUcVmElHLISAfXp/TgY3EwN07VCRsC',
        'CASHIER',
        true,
        now(),
        now(),
        'system',
        'system');